### ISSUE TITLE
IOHandler eval "NameError: name 'tzutc' is not defined" 

### ISSUE THREAD

**Issue by shahargl** [keephq/keep#138]
When rendering output of Datadog Provider, the library uses `dateutil.tz.tzutc` to express dates, and when "eval" is used in the handler, we are getting
```
eval(_arg)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
NameError: name 'tzutc' is not defined
```

**Comment by shahargl** [comment]
closed by https://github.com/keephq/keep/pull/136
