### ISSUE TITLE
[🐛 Bug]: Alerts From Kafka Provider Failed  

### ISSUE THREAD

**Issue by Riete** [keephq/keep#2823]
**Describe the bug**
if json message which missing "lastReceived" key sent to kafka topic, the alerts will not generated  

**To Reproduce**

1. add a kafka provider
2. send some json messages without "lastReceived" key 

**Expected behavior**
can receive alerts

**Screenshots**
N/A

**Additional context**
After some research and add trace code, I found when the messages sent to kafka topic missing " lastReceived" key, it will report  "Error pushing alert to API", and trace is as following:
```
{"asctime": "2024-12-13 10:02:06,099", "message": "1 validation error for AlertDto\nlastReceived\n  fromisoformat: argument must be str (type=type_error)", "levelname": "WARNING", "name": "275302b5bf8d48a38e6461d990370706", "filename": "kafka_provider.py", "otelTraceID": "0", "otelSpanID": "0", "otelServiceName": "keep-api", "threadName": "consumer-<keep.providers.kafka_provider.kafka_provider.KafkaProvider object at 0x7faf26897250>", "process": 20, "module": "kafka_provider", "otelTraceSampled": false, "tenant_id": "keep", "workflow_id": null, "workflow_execution_id": null, "context": [{}]}
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/keep/providers/kafka_provider/kafka_provider.py", line 256, in start_consume
    self._push_alert(record.value)
  File "/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py", line 681, in _push_alert
    alert_model = AlertDto(
                  ^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AlertDto
lastReceived
  fromisoformat: argument must be str (type=type_error)

{"asctime": "2024-12-13 10:02:06,100", "message": "Exception occurred", "levelname": "ERROR", "name": "root", "filename": "kafka_provider.py", "otelTraceID": "0", "otelSpanID": "0", "otelServiceName": "keep-api", "threadName": "consumer-<keep.providers.kafka_provider.kafka_provider.KafkaProvider object at 0x7faf26897250>", "process": 20, "module": "kafka_provider", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/providers/kafka_provider/kafka_provider.py\", line 256, in start_consume\n    self._push_alert(record.value)\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 681, in _push_alert\n    alert_model = AlertDto(\n                  ^^^^^^^^^\n  File \"pydantic/main.py\", line 341, in pydantic.main.BaseModel.__init__\npydantic.error_wrappers.ValidationError: 1 validation error for AlertDto\nlastReceived\n  fromisoformat: argument must be str (type=type_error)", "otelTraceSampled": false}
```
if sent messsage contains "lastReceived" key, the alerts will generate normally

**Comment by talboren** [comment]
@Riete Pushed a quick fix for this one. It should be fine now, if you pull the latest version. Let me know if it still occurs somehow.

**Comment by shahargl** [comment]
@Riete - @talboren fixed it, you can use the new release `0.31.8` with the fix.
